#!/bin/bash

nome_arquivo=$1




############################tasks###############################################
#TODO: CHECAR SE O USUARIO EXITE NA LISTA DE USUARIOS.

#TODO: CHECAR SE O USUARIO POSSUI AINDA POSSUI LIMITE PARA USAR.

#TODO: RETORNAR RELATORIO PARA O USUARIO QUANDO O PARAMETRO -f FOR PASSADO

#TODO: CHECAR SE OS ARQUIVOS AUXILIARES EXISTEM